### ISSUE TITLE
Inventory button vanishes when clicked in Potion puzzle and game is unplayable after.

### ISSUE THREAD

**Issue by gabbynewbery** [Jan-A00/TravellingStickSalesman_GAME#22]
**Describe the bug**
When you finish teh puzzle I went to click on the inventory bag and it vanished completely snd inventory did not pop up.
tried to click on map button and that does not work after other button vanished.

**To Reproduce**
1. Complete puzzles till Quescus.
2. Play through puzzle.
3. click the inventory button
4. Button disappears, and the map button does not work.

**Expected behavior**
expected the complete the puzzle and able to trade a stick with him, then him tell you were to head to next.

![Screenshot_1](https://user-images.githubusercontent.com/64582982/99975600-6cb8ba00-2ddd-11eb-9c1c-262214576271.png)

**Desktop (please complete the following information):**
windows 10 
playing version EOS-02

**Comment by TineKent** [comment]
Sam made fixes and pushed them to the Git.
