### ISSUE TITLE
Hover-Over Indicator

### ISSUE THREAD

**Issue by TinyLeggs** [Jan-A00/TravellingStickSalesman_GAME#5]
**TravellingStickSaleman_v001**

**REQUEST**

---

Some sort of indicator on button UI that indicates that you are hovering over it with your mouse cursor. The most common ones that I have seen was either a full colour change, or going from slightly desaturated as the default to fully saturated when hovered over.

**Comment by TineKent** [comment]
Hover indicator solved by using a white glow that appears when the cursor hovers over the item.

![UIHoverGlow](https://user-images.githubusercontent.com/64451303/92985543-378f1200-f4e6-11ea-8646-b2d468a48cfb.png)
