### ISSUE TITLE
Tutorial Restructure

### ISSUE THREAD

**Issue by TinyLeggs** [Jan-A00/TravellingStickSalesman_GAME#8]
**TravellingStickSalesman_v001**

**REQUEST**

Rework the Tutorial scene so that it flows better. There are currently too many contradictions and too much clicking happening. Look into shuffling then you click on things, or doing it in a way that the tutorial shows you **explicitly** how to do the thing that you want.

Rewrite with Narrative Lead and Design Lead.

**Comment by TineKent** [comment]
Feature request closed because it has been superseded by Feature Request #14
